"use client";

import type { ReactNode } from "react";

import type { Confidence } from "@/services/api/ai";

import type { Remote } from "./ai-assist-context";

const CONFIDENCE_CLASS: Record<Confidence, string> = {
  high: "border-success/40 text-success",
  medium: "border-warning/40 text-warning",
  low: "border-border text-fg-muted",
};

/** The model's own stated confidence, shown as a word (never as an invented percentage). */
export function ConfidenceLabel({ value }: { value: Confidence }) {
  return (
    <span
      title="Confidence as stated by the AI model"
      className={`rounded border px-1 text-[10px] leading-4 ${CONFIDENCE_CLASS[value]}`}
    >
      {value} confidence
    </span>
  );
}

export function AdvisoryFooter({
  provider,
  model,
  warnings,
  context,
}: {
  provider: string;
  model: string;
  warnings: readonly string[];
  context?: { used: boolean; files: readonly string[]; semantic_snippet_count?: number };
}) {
  return (
    <div className="space-y-1 border-t border-border pt-2 text-[11px] text-fg-subtle">
      {warnings.length > 0 && (
        <ul className="space-y-0.5 text-warning">
          {warnings.map((warning) => (
            <li key={warning}>{warning}</li>
          ))}
        </ul>
      )}
      {context?.used && (
        <p title={context.files.join("\n")}>
          Used project context from {context.files.length} file
          {context.files.length === 1 ? "" : "s"}
          {context.semantic_snippet_count
            ? ` (${context.semantic_snippet_count} found by semantic retrieval)`
            : ""}
          .
        </p>
      )}
      <p>
        Generated by {provider} ({model}). AI output is advisory; check it before relying on it.
      </p>
    </div>
  );
}

/** Loading / error / unavailable states shared by the AI panels. */
export function RemoteStatus<T>({
  result,
  loading,
  children,
}: {
  result: Remote<T>;
  loading: string;
  children(data: T): ReactNode;
}) {
  if (result.state === "idle") return null;
  if (result.state === "loading") {
    return (
      <p role="status" className="text-xs text-fg-muted">
        {loading}
      </p>
    );
  }
  if (result.state === "error") {
    const unavailable = result.code === "ai_disabled" || result.code === "ai_not_configured";
    return (
      <p
        role="alert"
        className={`rounded border px-2 py-1.5 text-xs ${
          unavailable ? "border-border text-fg-muted" : "border-danger/40 bg-danger/10 text-danger"
        }`}
      >
        {unavailable ? `AI unavailable: ${result.message}` : result.message}
      </p>
    );
  }
  return <>{children(result.data)}</>;
}
