"use client";

import type { ReactNode } from "react";

import type { Confidence } from "@/services/api/ai";

import type { Remote } from "./ai-assist-context";

const CONFIDENCE_CLASS: Record<Confidence, string> = {
  high: "border-success/40 text-success",
  medium: "border-warning/40 text-warning",
  low: "border-border text-fg-muted",
};

/** The model's own stated confidence, shown as a word (never as an invented percentage). */
export function ConfidenceLabel({ value }: { value: Confidence }) {
  return (
    <span
      title="Confidence as stated by the AI model"
      className={`rounded border px-1 text-[10px] leading-4 ${CONFIDENCE_CLASS[value]}`}
    >
      {value} confidence
    </span>
  );
}

export function AdvisoryFooter({
  provider,
  model,
  warnings,
  context,
}: {
  provider: string;
  model: string;
  warnings: readonly string[];
  context?: { used: boolean; files: readonly string[]; semantic_snippet_count?: number };
}) {
  return (
    <div className="space-y-1 border-t border-border pt-2 text-[11px] text-fg-subtle">
      {warnings.length > 0 && (
        <ul className="space-y-0.5 text-warning">
          {warnings.map((warning) => (
            <li key={warning}>{warning}</li>
          ))}
        </ul>
      )}
      {context?.used && (
        <p title={context.files.join("\n")}>
          Used project context from {context.files.length} file
          {context.files.length === 1 ? "" : "s"}
          {context.semantic_snippet_count
            ? ` (${context.semantic_snippet_count} found by semantic retrieval)`
            : ""}
          .
        </p>
      )}
      <p>
        Generated by {provider} ({model}). AI output is advisory; check it before relying on it.
      </p>
    </div>
  );
}

/** Short, safe reasons for the backend's normalized AI error codes. */
const AI_UNAVAILABLE_REASONS: Record<string, string> = {
  ai_quota_exceeded: "provider quota exceeded",
  ai_auth_failed: "authentication failed",
  ai_model_unavailable: "model not available",
  ai_rate_limited: "provider rate limit reached",
  ai_timeout: "provider timed out",
  ai_unavailable: "provider could not be reached",
  ai_disabled: "AI is turned off on this server",
  ai_not_configured: "AI is not configured on this server",
};

const AI_FAILED_REASONS: Record<string, string> = {
  ai_provider_error: "the provider rejected the request",
  ai_malformed_response: "the answer could not be used",
  ai_context_too_large: "the request is too large",
  ai_refused: "the provider declined the request",
};

/** The short reason for an AI error code ("provider quota exceeded"), if it is a known one. */
export function aiErrorReason(code: string | null | undefined): string | undefined {
  if (!code) return undefined;
  return AI_UNAVAILABLE_REASONS[code] ?? AI_FAILED_REASONS[code];
}

/**
 * An AI failure with its reason ("AI unavailable / Reason: provider quota exceeded") and the
 * backend's message. Unknown codes show only the message.
 */
export function AiErrorNotice({ code, message }: { code?: string | null; message: string }) {
  const unavailable = code ? AI_UNAVAILABLE_REASONS[code] : undefined;
  const reason = unavailable ?? (code ? AI_FAILED_REASONS[code] : undefined);
  if (!reason) {
    return (
      <p role="alert" className="text-xs text-danger">
        {message}
      </p>
    );
  }
  const off = code === "ai_disabled" || code === "ai_not_configured";
  return (
    <div
      role="alert"
      className={`space-y-0.5 rounded border px-2 py-1.5 text-xs ${
        off ? "border-border text-fg-muted" : "border-danger/40 bg-danger/10 text-danger"
      }`}
    >
      <p className="font-semibold">{unavailable ? "AI unavailable" : "AI request failed"}</p>
      <p>Reason: {reason}</p>
      {message && <p className="text-fg-muted">{message}</p>}
    </div>
  );
}

/** Loading / error / unavailable states shared by the AI panels. */
export function RemoteStatus<T>({
  result,
  loading,
  children,
}: {
  result: Remote<T>;
  loading: string;
  children(data: T): ReactNode;
}) {
  if (result.state === "idle") return null;
  if (result.state === "loading") {
    return (
      <p role="status" className="text-xs text-fg-muted">
        {loading}
      </p>
    );
  }
  if (result.state === "error") {
    return <AiErrorNotice code={result.code} message={result.message} />;
  }
  return <>{children(result.data)}</>;
}
