"""initial schema

Revision ID: 32a816011f6f
Revises:
Create Date: 2026-09-30 23:39:44.984330

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32a816011f6f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("root_path", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index("uq_projects_lower_name", "projects", [sa.literal_column("lower(name)")], unique=True)
    op.create_table(
        "files",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("structure", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_files_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("project_id", "path", name="uq_files_project_id_path"),
    )
    op.create_index(op.f("ix_files_project_id"), "files", ["project_id"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "analysis_type",
            sa.Enum(
                "code",
                "project_intelligence",
                name="analysis_type",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "completed",
                "partial",
                "failed",
                name="analysis_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("diagnostic_count", sa.Integer(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "analysis_type IN ('code', 'project_intelligence')", name=op.f("ck_analyses_analysis_type")
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'partial', 'failed')", name=op.f("ck_analyses_analysis_status")
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_analyses_file_id_files"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_analyses_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
    )
    op.create_index("ix_analyses_file_id_created_at", "analyses", ["file_id", "created_at"], unique=False)
    op.create_index(
        "ix_analyses_project_id_created_at", "analyses", ["project_id", "created_at"], unique=False
    )
    op.create_table(
        "diagnostics",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "error",
                "warning",
                "information",
                "suggestion",
                name="diagnostic_severity",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "syntax",
                "lint",
                "style",
                "type",
                "semantic",
                name="diagnostic_category",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("rule_code", sa.String(length=64), nullable=True),
        sa.Column("file_path", sa.String(length=1024), nullable=True),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.Column("column", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("end_column", sa.Integer(), nullable=False),
        sa.Column("suggestion", sa.Text(), nullable=True),
        sa.Column("documentation_url", sa.String(length=512), nullable=True),
        sa.Column("fixable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IN ('syntax', 'lint', 'style', 'type', 'semantic')",
            name=op.f("ck_diagnostics_diagnostic_category"),
        ),
        sa.CheckConstraint(
            "severity IN ('error', 'warning', 'information', 'suggestion')",
            name=op.f("ck_diagnostics_diagnostic_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_diagnostics_analysis_id_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostics")),
    )
    op.create_index(op.f("ix_diagnostics_analysis_id"), "diagnostics", ["analysis_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagnostics_analysis_id"), table_name="diagnostics")
    op.drop_table("diagnostics")
    op.drop_index("ix_analyses_project_id_created_at", table_name="analyses")
    op.drop_index("ix_analyses_file_id_created_at", table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_files_project_id"), table_name="files")
    op.drop_table("files")
    op.drop_index("uq_projects_lower_name", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
